### ISSUE TITLE
Why no css file?

### ISSUE THREAD

**Issue by mika76** [Deveo/emojione-png-sprites#1]
I see only a SCSS file - why not generate css ones for your dist folder?

**Comment by lolmaus** [comment]
Because CSS spritesheets don't allow customization and are offered by EmojiOne in the first place:

https://github.com/emojione/emojione/tree/2.2.7/assets/css

They come in 32, 128 and 512 sizes.

**Comment by mika76** [comment]
But not with a spritesheet as far as I understand? emojione-awesome is what I'm looking for, but don't like that each image is downloaded separately...

**Comment by lolmaus** [comment]
Sorry, wrong link. Looks like they only have 32px and SVG sprites available:

https://github.com/emojione/emojione/tree/2.2.7/assets/sprites

You can also produce CSS from the Sass mixin provided by this package.

**Comment by lolmaus** [comment]
We don't supply a CSS file because we don't make assumptions on how your HTML is organized.

You can generate the CSS file tailored to your needs using our Sass mixin.

**Comment by lolmaus** [comment]
We don't supply a CSS file because we don't make assumptions on ~~how your HTML is organized~~ which HTML size (or sizes!) you need, which retina scale factors you want to support and what path you're gonna serve the spritesheets from.

You can generate the CSS file tailored to your needs using our Sass mixin. If you don't use Sass in your webapp/site, you can do it by hand once.

PS Don't forget to star the repo. ;)
